name: push-ci

on:
  push:
    branches:
      - '**'
  release:
    types:
      - created
env:
  node_version: 12.x

jobs:
  testAndCoverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node_version }}
    - run: npm install
    - run: npm run test
    - run: npm run coverage
    - env:
        repo-token: ${{ github.token }}
        repository: ${{ github.repository }}
        GITHUB_TOKEN: ${{ github.token }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: npm run pushCoverageReport

  publish:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node_version }}
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm run build
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}